Style/StringLiterals:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
