Style/StringLiterals:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 40

Naming/VariableNumber:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

# Wait until https://github.com/rubocop/rubocop/issues/8761 is fixed
Gemspec/RequiredRubyVersion:
  Enabled: false